FROM rust:1.68.0 AS broadcast_build
WORKDIR /usr/src

RUN apt update ; apt install -y musl-tools
RUN rustup target add x86_64-unknown-linux-musl

RUN USER=root cargo new broadcast
WORKDIR /usr/src/broadcast
COPY Cargo.toml ./
COPY src ./src
RUN cargo build --release  --target=x86_64-unknown-linux-musl

FROM alpine AS broadcast_service
EXPOSE 3030
COPY --from=broadcast_build /usr/src/broadcast/target/x86_64-unknown-linux-musl/release/broadcast .
USER 1000
CMD ["./broadcast"]