[package]
name = "detect_card"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
tesseract = "0.14.0"

[dev-dependencies]
image = "0.24.6"
