[package]
name = "detect_card"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-global-executor = "2.3.1"
clap = { version = "4.3.0", features = ["derive"] }
env_logger = "0.10.0"
futures = { version = "0.3.17", default-features = true }
lapin = "2.2.1"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
tesseract = "0.14.0"
tokio = { version = "1", features = ["macros", "time", "rt-multi-thread"] }

[dev-dependencies]
image = "0.24.6"
