[package]
name = "detect_card"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-global-executor = "2"
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
futures = { version = "0.3", default-features = true }
lapin = "2"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tesseract = { version="^0.15", default-features = false}
tokio = { version = "1", features = ["macros", "time", "rt-multi-thread"] }

[dev-dependencies]
image = "0.24"
