FROM python:3.10-slim-bullseye AS lib
RUN apt update; apt -y upgrade; apt install -y tesseract-ocr
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY detect_card.py ./
COPY keywords_cards.json ./

FROM lib AS acceptance_tests
RUN pip install pytest
COPY tests/*.jpg ./tests/
COPY tests/test_* ./tests/
ENV PYTHONPATH .
CMD ["pytest","tests"]  

FROM lib AS rabbit_service
RUN pip install pika
COPY serve_detect_card.py ./
ARG RMQSERVER=localhost
ENV RABBITMQSERVER=$RMQSERVER
EXPOSE 5672
EXPOSE 15672
CMD ["python","serve_detect_card.py"]