[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
pre-build = [
    "dpkg --add-architecture arm64 ",
    "apt-get update ",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils libc6-dev:arm64 libleptonica-dev:arm64 libtesseract-dev:arm64 clang",
]