version: '3'

services:
  rabbitmq:
    image: docker.io/rabbitmq:3.11-management
    ports:
      - '5672:5672'
      - '15672:15672'

  detect_card:
    image: localhost/detect_card_service
    depends_on:
      - rabbitmq
    environment:
      # The location of the RabbitMQ server.  "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      RABBITMQ_AMQP_URL: amqp://rabbitmq

