[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
async-global-executor = "2.3.1"
clap = { version = "4.3.0", features = ["derive"] }
env_logger = "0.10.0"
image = "0.24.5"
lapin = "2.1.1"
log = "0.4.17"
nokhwa = { version = "0.10.3", features = ["input-native"] }
