[package]
name = "monitor"
version.workspace = true
edition = "2021"

[dependencies]
async-global-executor = "2"
clap = { workspace = true, features = ["derive"] }
env_logger.workspace = true
image = "0.24"
lapin.workspace = true
log.workspace = true
v4l = "0.14.0"
