[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
async-global-executor = "2"
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
image = "0.24"
lapin = "2"
log = "0.4"
v4l = "0.14.0"
