#pragma once

#define INC_LEFT_BUTTON_PIN 17
#define DEC_LEFT_BUTTON_PIN 16
#define INC_RIGHT_BUTTON_PIN 19
#define DEC_RIGHT_BUTTON_PIN 18
#define NEXT_SCREEN_BUTTON_PIN 20
#define PREVIOUS_SCREEN_BUTTON_PIN 21

#define CONNECETED_LED_PIN 5
#define HERO_READY_LED_PIN 4
#define HERO_DONE_LED_PIN 3
#define HERO_ORDER_LED_PIN 2

#define CONNECTION_CONNECTED 2
#define CONNECTION_DISCONNECTED 1
#define CONNECTION_OFFLINE 0

#define MOVE_ACTION 0
#define FIGHT_ACTION 1
#define GUARD_ACTION 2
#define REST_ACTION 3
#define EVADE_ACTION 4
#define AIM_ACTION 5
#define PROLONGED_ACTION 6
#define SECOND_HALF_ACTION_UNAVAILABLE 7

#define HERO_READY 0
#define HERO_DONE 1

// SCREENS
#define HEADER_X 0
#define HEADER_Y 50
#define HEADER_IMAGE_WIDTH 16
#define HEADER_IMAGE_HEIGHT 60
#define LEFT_ICON_X 34
#define LEFT_ICON_Y 84
#define LEFT_ICON_WIDTH 52
#define LEFT_ICON_HEIGHT 51
#define CENTER_ICON_X 34
#define CENTER_ICON_Y 43
#define CENTER_ICON_WIDTH 52
#define CENTER_ICON_HEIGHT 62
#define RIGHT_ICON_X 34
#define RIGHT_ICON_Y 25
#define RIGHT_ICON_WIDTH 51
#define RIGHT_ICON_HEIGHT 51
#define NAVI_X 108
#define NAVI_Y 52
#define NAVI_IMAGE_WIDTH 18
#define NAVI_IMAGE_HEIGHT 57

#define FIRST_SCREEN 0
#define LIFE_SCREEN 0
#define ACTION_SCREEN 1
#define COIN_SMALL_SCREEN 2
#define COIN_BIG_SCREEN 3
#define POTIONS_1_SCREEN 4
#define POTIONS_2_SCREEN 5
#define POTIONS_3_SCREEN 6
#define STATUS_1_SCREEN 7
#define STATUS_2_SCREEN 8
#define STATUS_3_SCREEN 9
#define STATUS_4_SCREEN 10
#define TRAINING_1_SCREEN 11
#define TRAINING_2_SCREEN 12
#define LAST_SCREEN 12