[package]
name = "identify_game_scene"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
futures = { version = "0.3", default-features = true }
lapin = "2"
log = "0.4"
opencv = { version="0.88", features = ["clang-runtime"]}
tokio = { version = "1", features = ["macros", "time", "rt-multi-thread"] }
rustix = "0.37.25"
