[package]
name = "identify_game_scene"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
env_logger = "0.10.0"
futures = { version = "0.3.17", default-features = true }
lapin = "2.3.1"
log = "0.4.19"
opencv = "0.83.0"
tokio = { version = "1", features = ["macros", "time", "rt-multi-thread"] }
