[package]
name = "presentation"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
gloo = { version = "0.11.0", features = ["futures"] }
leptos = { version = "0.6.15", features = ["csr"] }
rand = "0.8.5"
thaw = { git = "https://github.com/thaw-ui/thaw", branch = "thaw-v0.3", features = [
    "csr",
] }
