[package]
name = "presentation"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
js-sys = "0.3.72"
leptos = { version = "0.6.15", features = ["csr"] }
reqwest = { version = "0.12", features = ["json"] }
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3.72", features = ["Blob", "Url"] }
