[package]
name = "presentation"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
leptos = { version = "0.6.15", features = ["csr"] }
thaw = { git = "https://github.com/thaw-ui/thaw", branch = "thaw-v0.3", features = [
    "csr",
] }
